# Generated by Django 5.2.3 on 2025-07-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
